### ISSUE TITLE
Access token provider returned a null access token

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/dlldistributionserver#84]
```
java.lang.IllegalStateException: Access token provider returned a null access token, which is illegal according to the contract.
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:223)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
    at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:105)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fil
```

**Comment by matanki-saito** [comment]
![image](https://user-images.githubusercontent.com/35730970/66730986-d2730c80-ee8f-11e9-89de-f567dad1f4bb.png)

**Comment by matanki-saito** [comment]
トークンを艇に入れるメソッド名が、get->acquire->obtainとなっていくのおもしろいな
http://eitangotsukaiwake.suntomi.com/index.php?get%2C%20earn%2C%20gain%2C%20acquire%2C%20obtain

**Comment by matanki-saito** [comment]
もしかして、githubのoauth2にはrefreshトークンの仕組みがないのか？
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

**Comment by matanki-saito** [comment]
トークンはexpireしないらしい
https://stackoverflow.com/questions/26902600/whats-the-lifetime-of-github-oauth-api-access-token

**Comment by matanki-saito** [comment]
おそらく、何らかの理由でクッキーのセッションに紐づくアクセストークンがredisから消えてしまった場合に、https://github.com/login/oauth/access_tokenを使ってリクエストするのだが、codeやstateなどを使いまわすため、それはexpireされていて、nullになってしまうのだと思う。

**Comment by matanki-saito** [comment]
Spring securityのupdate により解決された
